AppBundle\Entity\Recruit:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\RecruitRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        email:
            type: string
            length: 255
        name:
            type: string
            length: 255
        fname:
            type: string
            length: 255
        phone:
            type: integer
        birth:
            type: datetime
        cv:
            type: string
            length: 255
    lifecycleCallbacks: {  }
