<?php

namespace AppBundle\Repository;

/**
 * RDVRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RDVRepository extends \Doctrine\ORM\EntityRepository
{
}
