<?php

namespace AppBundle\Repository;

/**
 * RecruitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecruitRepository extends \Doctrine\ORM\EntityRepository
{
}
